server:
  port: 9292

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  secret-key: ${JWT_SECRET_KEY}
  header: ${JWT_HEADER}
  token-prefix: ${JWT_TOKEN_PREFIX}
  access-token-duration: ${JWT_ACCESS_TOKEN_DURATION}
  refresh-token-duration: ${JWT_REFRESH_TOKEN_DURATION}